// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X.Scheduler;

namespace X.Scheduler.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180815135339_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("X.Scheduler.Data.Entitites.Schedule", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<short>("Shift");

                    b.Property<string>("StaffGuidId")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("X.Scheduler.Data.Entitites.Staff", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Title");

                    b.HasKey("Guid");

                    b.ToTable("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
